name: CI

on: 
  push:
  watch:
    types: [started]
  # schedule:
  #   - cron: '10 0,10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Cache
        uses: actions/cache@v1
        env:
          cache-name: cache-ncovdata
        with:
          path: ~/.ncovdata
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: r-setup
        uses: r-lib/actions/setup-r@v1
        
      - name: sys-require
        run: sudo apt-get install -y libcurl4-openssl-dev
        
      - name: get_ncov
        run: Rscript get_ncov.R
        
      - name: auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with: 
          commit_message: automatic update for changes detected
